FROM {{ namespace }}/{{ image_prefix }}glance-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block hostbill_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro not in ['debian', 'ubuntu'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
&& /bin/false

{% endif %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{{ macros.install_packages(hostbill_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_hostbill_extend_start
RUN chmod 755 /usr/local/bin/kolla_hostbill_extend_start

{% block hostbill_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER hostbill
